# -- Override the name of the chart
nameOverride: ""
# -- Override the full name of the chart
fullnameOverride: ""
# -- Override the namespace of the chart
namespaceOverride: ""

service:
  create: false
  additionalLabels: {}
  annotations: {}
  ports:
  - port: 61616
    targetPort: 61616
  type: ClusterIP

broker:
  version: "2.42.0"
  adminPassword: null
  adminUser: null
  acceptors:
     - name: artemis
       bindToAllInterfaces: true
       port: 61616
       protocols: all
  connectors: {}
  console: null
  ingressDomain: null
  deploymentPlan:
    size: 1
    resources: {}
    extraMounts: []

  env: []
  additionalLabels: {}
  annotations: {}
  resourceTemplates: []
  properties: []
  restricted: false

jaasConfig:
  create: false
  annotations: {}
  loginConfig: |
    activemq {
            // ensure the operator can connect to the broker by referencing the existing properties config
            org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
                org.apache.activemq.jaas.properties.user="artemis-users.properties"
                org.apache.activemq.jaas.properties.role="artemis-roles.properties"
                baseDir="/home/jboss/amq-broker/etc";

            org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
                reload=true
                org.apache.activemq.jaas.properties.user="users.properties"
                org.apache.activemq.jaas.properties.role="roles.properties";

    };

  rolesProperties: ""
  usersProperties: ""

loggingConfig:
  create: false
  annotations: {}
  loggingProperties: ""

brokerProperties:
  create: false
  annotations: {}
  jsonConfig: {}
    #addressSettings:
    #  "#":
    #    redistributionDelay: 60000
    #    maxDeliveryAttempts: 2
  secrets: []

